server:
  port: 9393
  servlet:
      context-path: /
      encoding:
        charset: UTF-8
        enabled: true
        force: true

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/pro?serverTimeZone=Asia/Seoul
      username: pro
      password: pro01!
  application:
    name: im-project
  thymeleaf:
    cache: false

jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: auto
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        hql:
          bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy
        jdbc:
          batch_size: 20
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 500
        show_sql: true
        format_sql: true	

logging:
  level:
    org.hibernate.type: debug